imagePullSecret: azure-docker-registry

keyVault:
  name: key-vault-name
  secrets: []
  multiValueSecrets: []
  envSpecific:
    secrets: []
    multiValueSecrets: []

functions:
  horizonCreateContact:
    image: pinscommonukscontainers3887default.azurecr.io/horizon-create-contact:latest
    scale:
      min: 1
      max: 5
    timeout: 10s
    envvars:
      HORIZON_URL: http://10.0.7.4:8000
    secrets: []

  horizonHouselderAppealPublish:
    image: pinscommonukscontainers3887default.azurecr.io/horizon-householder-appeal-publish:latest
    scale:
      min: 1
      max: 5
    timeout: 90s
    envvars:
      APPEALS_SERVICE_URL: http://app.app-ENV.svc.cluster.local:3000
      GATEWAY_URL: http://gateway.openfaas.svc.cluster.local:8080
      HORIZON_URL: http://10.0.7.4:8080
    secrets: []
