parameters:
  - name: region
    displayName: Region
    type: string
    values:
      - UK West
      - UK South
    default: UK West

trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/2.0.0
  pipelines:
    - pipeline: horizon-functions-ci
      source: horizon-functions CI
      trigger: 
        branches:
          include: 
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    artifact: azure-functions
    deploymentStages:
      - name: Deploy
        deploymentSteps:
          - template: ../steps/function_app_deploy.yml
            parameters:
              appName: $(functionAppName)
              resourceGroup: $(resourceGroup)
    downloadArtifact: true
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: packages/horizon-functions/pipelines/azure-pipelines-variables.yml@self
    sourcePipeline: horizon-functions CI
