trigger:
  paths:
    include:
      - packages/horizon-functions

pr:
  branches:
    include:
      - master
  paths:
    include:
      - packages/horizon-functions

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: packages/horizon-functions/pipelines/azure-pipelines-variables.yml@self
    pool:
      vmImage: ubuntu-latest
    projectName: $(projectName)
    validateName: Build
    validationSteps:
      - script: |
          buildName=$(versionNumber)_$(Build.BuildId)
          echo "Setting the name of the build to '$buildName'."
          echo "##vso[build.updatebuildnumber]$buildName"
        displayName: Set Build Number
      - script: |
          echo "Setting build tag to '$(Build.SourceBranchName)'."
          echo "##vso[build.addbuildtag]$(Build.SourceBranchName)"
        displayName: Add Branch Tag
      - template: steps/function_app_validate.yml@templates
        parameters:
          workingDirectory: $(Build.Repository.LocalPath)/packages/horizon-functions
