---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-dev
  annotations:
    fluxcd.io/automated: 'false'
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    globals:
      domainNames:
        appealsWebApp: appeals-dev.planninginspectorate.gov.uk
        lpaQuestionnaireWebApp: lpa-questions-dev.planninginspectorate.gov.uk

    appealReplyServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeal-reply-service-api
        tag: 1.10.1
      config:
        notify:
          secretName: akv-notify-preprod

    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeals-service-api
        tag: 1.19.0
      config:
        notify:
          secretName: akv-notify-preprod

    documentServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/document-service-api
        tag: 1.4.1

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/forms-web-app
        tag: 1.47.4
      config:
        googleAnalyticsId: G-TZBWMVPTHV

    lpaQuestionnaireWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/lpa-questionnaire-web-app
        tag: 1.33.1

    pdfServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/pdf-service-api
        tag: 1.0.3

    queueRetryService:
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/queue-retry
        tag: 1.0.1

    gotenberg:
      replicaCount: 2

    keyVault:
      name: pins-uks-vault-8669-dev
      envSpecific:
        multiValueSecrets:
          - http-basic

    pinsKeyVault:
      envSpecific:
        secrets:
          - notify-preprod

    ingress:
      hosts:
        fwa:
          host: appeals-dev.planninginspectorate.gov.uk
        lpaq:
          host: lpa-questions-dev.planninginspectorate.gov.uk
      httpBasic:
        enabled: true
        secret: akv-http-basic

    horizon-householder-appeal-publish:
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/openfaas-amqp1.0-connector
        tag: 1.0.0
      amqp:
        connection:
          host: pins-uks-message-queue-dev.servicebus.windows.net
          hostname: pins-uks-message-queue-dev.servicebus.windows.net
