---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-dev
  annotations:
    fluxcd.io/automated: "true"
    # Add hyphen to include pre-releases
    filter.fluxcd.io/appealReplyServiceApi: semver:^1.0.0-0
    filter.fluxcd.io/appealsServiceApi: semver:^1.0.0-0
    filter.fluxcd.io/documentServiceApi: semver:^1.0.0-0
    filter.fluxcd.io/formsWebApp: semver:^1.0.0-0
    filter.fluxcd.io/horizon-householder-appeal-publish: semver:^1.0.0-0
    filter.fluxcd.io/lpaQuestionnaireWebApp: semver:^1.0.0-0
    filter.fluxcd.io/pdfServiceApi: semver:^1.0.0-0
    filter.fluxcd.io/queueRetryService: semver:^1.0.0-0
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    appealReplyServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeal-reply-service-api
        tag: 1.3.1

    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeals-service-api
        tag: 1.15.3
      config:
        notify:
          secretName: akv-notify-preprod

    documentServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/document-service-api
        tag: 1.4.0

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/forms-web-app
        tag: 1.46.0
      config:
        googleAnalyticsId: G-TZBWMVPTHV

    lpaQuestionnaireWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/lpa-questionnaire-web-app
        tag: 1.17.0

    pdfServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/pdf-service-api
        tag: 1.0.1

    queueRetryService:
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/queue-retry
        tag: 1.0.0

    gotenberg:
      replicaCount: 2

    keyVault:
      name: pins-uks-vault-8669-dev
      envSpecific:
        multiValueSecrets:
        - http-basic

    pinsKeyVault:
      envSpecific:
        secrets:
        - notify-preprod

    ingress:
      hosts:
        fwa:
          host: appeals-dev.planninginspectorate.gov.uk
        lpaq:
          host: lpa-questions-dev.planninginspectorate.gov.uk
      httpBasic:
        enabled: true
        secret: akv-http-basic

    horizon-householder-appeal-publish:
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/openfaas-amqp1.0-connector
        tag: 1.0.0
      amqp:
        connection:
          host: pins-uks-message-queue-dev.servicebus.windows.net
          hostname: pins-uks-message-queue-dev.servicebus.windows.net
