---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/tag.appealsServiceApi: semver:^1.0
    filter.fluxcd.io/tag.formsWebApp: semver:^1.0
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainersdefault.azurecr.io/appeals-service-api
        tag: 1.0.0

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainersdefault.azurecr.io/forms-web-app
        tag: 1.1.2

    ingress:
      host: appeals-dev.planninginspectorate.gov.uk
