---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: functions
  namespace: openfaas-fn
  annotations:
    fluxcd.io/automated: 'false'
spec:
  releaseName: functions
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/functions
  values:
    keyVault:
      name: pins-uks-vault-8669-dev

    pingHorizon:
      replicaCount: 1
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/ping
        tag: 1.0.0
      config:
        ping:
          url: http://10.0.7.4:8001/status

    functions:
      horizon-add-document:
        image: pinscommonukscontainers3887default.azurecr.io/horizon-add-document
        tag: 1.2.12
        envvars:
          DOCUMENT_SERVICE_URL: http://app.app-dev.svc.cluster.local:3001
          HORIZON_URL: http://10.0.7.4:8000

      horizon-create-contact:
        image: pinscommonukscontainers3887default.azurecr.io/horizon-create-contact
        tag: 1.1.0
        envvars:
          HORIZON_URL: http://10.0.7.4:8000

      horizon-householder-appeal-publish:
        image: pinscommonukscontainers3887default.azurecr.io/horizon-householder-appeal-publish
        tag: 1.4.9
        envvars:
          APPEALS_SERVICE_URL: http://app.app-dev.svc.cluster.local:3000
          DOCUMENT_SERVICE_URL: http://app.app-dev.svc.cluster.local:3001
          GATEWAY_URL: http://gateway.openfaas.svc.cluster.local:8080
          HORIZON_URL: http://10.0.7.4:8000
