---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/appealsServiceApi: semver:^1.0
    filter.fluxcd.io/documentServiceApi: semver:^1.0
    filter.fluxcd.io/formsWebApp: semver:^1.0
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainersdefault.azurecr.io/appeals-service-api
        tag: 1.6.0

    documentServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainersdefault.azurecr.io/document-service-api
        tag: 1.0.1

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainersdefault.azurecr.io/forms-web-app
        tag: 1.12.0-mongodb-session

    keyVault:
      name: pins-uks-vault-7324-dev

    ingress:
      host: appeals-dev.planninginspectorate.gov.uk
