# OpenFaaS Role
#
# Users are limited in what they can do. They are able to
# have read access to most things, but have no access to secrets
# (except listing).
#
# This is designed to be given to anyone who is a developer on the
# application. For the most part, this will enable them to read logs
# and make sure that things have deployed correctly.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfaas-user-access
  namespace: openfaas
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-user-group
  namespace: openfaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfaas-user-access
subjects:
  - kind: Group
    namespace: openfaas
    name: $GROUP_USER_ID
