parameters:
  - name: buildAppealsApi
    displayName: Build Appeals Service API
    type: boolean
    default: true
  - name: buildClamAv
    displayName: Build ClamAV API
    type: boolean
    default: false
  - name: buildDocumentsApi
    displayName: Build Documents Service API
    type: boolean
    default: false
  - name: buildHorizonFunctions
    displayName: Build Horizon Functions
    type: boolean
    default: true
  - name: buildPdfApi
    displayName: Build PDF Service API
    type: boolean
    default: false
  - name: buildWeb
    displayName: Build Web
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.0.3

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    globalVariables:
      - template: azure-pipelines-variables.yml@self
    validationJobs:
      - name: Run Linting & Tests
        steps:
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 14
              script: make install
          - template: ../steps/node_script.yml
            parameters:
              condition: succeededOrFailed()
              script: npm run lint
              nodeVersion: 14
          - template: ../steps/node_script.yml
            parameters:
              condition: succeededOrFailed()
              script: npm run test
              nodeVersion: 14
          - template: ../steps/node_script.yml
            parameters:
              condition: and(succeededOrFailed(),eq(variables['Build.SourceBranchName'], 'main'))
              script: npm run integration-test
              nodeVersion: 14
          - template: ../steps/check_changed_files.yml
            parameters:
              pathFilters:
                - name: appeals-api
                  path: packages/appeals-service-api
                - name: business-rules
                  path: packages/business-rules
                - name: clamav
                  path: packages/clamav-rest-server
                - name: common
                  path: packages/common
                - name: documents-api
                  path: packages/document-service-api
                - name: horizon-functions
                  path: packages/horizon-functions
                - name: pdf-api
                  path: packages/pdf-service-api
                - name: web
                  path: packages/forms-web-app
              stepName: check_files
      - name: Build Appeals API
        condition: >-
          and(
            succeeded(),
            or(
              and(
                eq(variables['Build.Reason'], 'Manual'),
                eq(${{ parameters.buildAppealsApi }}, 'true')
              ),
              and(
                ne(variables['Build.Reason'], 'Manual'),
                or(
                  eq(variables['Build.SourceBranchName'], 'main'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.appeals-api'], 'true'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.business-rules'], 'true'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.common'], 'true')
                )
              )
            )
          )
        dependsOn:
          - Run Linting & Tests
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.SourcesDirectory)/packages/appeals-service-api/Dockerfile
              repository: appeal-planning-decision/appeals-service-api
      - name: Build ClamAV Service
        condition: >-
          and(
            succeeded(),
            or(
              and(
                eq(variables['Build.Reason'], 'Manual'),
                eq(${{ parameters.buildClamAv }}, 'true')
              ),
              and(
                ne(variables['Build.Reason'], 'Manual'),
                or(
                 eq(variables['Build.SourceBranchName'], 'main'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.clamav'], 'true'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.common'], 'true')
                )
              )
            )
          )
        dependsOn:
          - Run Linting & Tests
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.SourcesDirectory)/packages/clamav-rest-server/Dockerfile
              repository: appeal-planning-decision/clamav-api
      - name: Build Documents API
        condition: >-
          and(
            succeeded(),
            or(
              and(
                eq(variables['Build.Reason'], 'Manual'),
                eq(${{ parameters.buildDocumentsApi }}, 'true')
              ),
              and(
                ne(variables['Build.Reason'], 'Manual'),
                or(
                  eq(variables['Build.SourceBranchName'], 'main'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.documents-api'], 'true'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.common'], 'true')
                )
              )
            )
          )
        dependsOn:
          - Run Linting & Tests
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.SourcesDirectory)/packages/document-service-api/Dockerfile
              repository: appeal-planning-decision/documents-api
      - name: Build Horizon Functions
        condition: >-
          and(
            succeeded(),
            or(
              and(
                eq(variables['Build.Reason'], 'Manual'),
                eq(${{ parameters.buildHorizonFunctions }}, 'true')
              ),
              and(
                ne(variables['Build.Reason'], 'Manual'),
                or(
                  eq(variables['Build.SourceBranchName'], 'main'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.horizon-functions'], 'true')
                )
              )
            )
          )
        dependsOn:
          - Run Linting & Tests
        steps:
          - template: ../steps/function_app_validate.yml@templates
            parameters:
              nodeVersion: 14
              workingDirectory: $(Build.Repository.LocalPath)/packages/horizon-functions
      - name: Build PDF Service
        condition: >-
          and(
            succeeded(),
            or(
              and(
                eq(variables['Build.Reason'], 'Manual'),
                eq(${{ parameters.buildPdfApi }}, 'true')
              ),
              and(
                ne(variables['Build.Reason'], 'Manual'),
                or(
                  eq(variables['Build.SourceBranchName'], 'main'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.pdf-api'], 'true')
                )
              )
            )
          )
        dependsOn:
          - Run Linting & Tests
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.Repository.LocalPath)/packages/pdf-service-api/Dockerfile
              repository: appeal-planning-decision/pdf-service-api

      - name: Build Web
        condition: >-
          and(
            succeeded(),
            or(
              and(
                eq(variables['Build.Reason'], 'Manual'),
                eq(${{ parameters.buildWeb }}, 'true')
              ),
              and(
                ne(variables['Build.Reason'], 'Manual'),
                or(
                  eq(variables['Build.SourceBranchName'], 'main'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.business-rules'], 'true'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.common'], 'true'),
                  eq(dependencies.run_linting_and_tests.outputs['check_files.web'], 'true')
                )
              )
            )
          )
        dependsOn:
          - Run Linting & Tests
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.Repository.LocalPath)/packages/forms-web-app/Dockerfile
              repository: appeal-planning-decision/forms-web-app
