pr: none
trigger: none

schedules:
  - cron: "0 7 * * 1-5"
    displayName: Weekday 07:00 Cleanup
    branches:
      include:
      - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.20.0

pool: pins-odt-agent-pool

variables:
  - group: pipeline_secrets

jobs:
  - job: purge
    displayName: Cleanup Container Registry Images
    steps:
      - template: steps/azure_auth.yml@templates
        parameters:
          subscriptionId: edb1ff78-90da-4901-a497-7e79f966f8e2
      - template: steps/azure_container_registry_purge.yml@templates
        parameters:
          azurecrName: pinscrsharedtoolinguks
          repositories: > 
            [
              "appeal-planning-decision/appeals-service-api",
              "appeal-planning-decision/auth-server",
              "appeal-planning-decision/documents-api",
              "appeal-planning-decision/forms-web-app",
              "appeal-planning-decision/pdf-service-api"
            ]
    workspace:
      clean: all
