parameters:
  - name: keepLastXDays
    displayName: Keep Last X Days
    type: number
    default: 60
  - name: dryRun
    displayName: Dry Run (don't delete)
    type: boolean
    default: false

pr: none
trigger: none

# run on weekly schedule
schedules:
  - cron: '0 7 * * 1'
    displayName: Monday 07:00 Purge
    branches:
      include:
        - main

pool: pins-odt-agent-pool

variables:
  - group: pipeline_secrets

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.21.0

jobs:
  - job: purge
    displayName: Cleanup Container Registry Images
    steps:
      - checkout: self
      - checkout: templates
      - template: steps/azure_auth.yml@templates
        parameters:
          subscriptionId: edb1ff78-90da-4901-a497-7e79f966f8e2
      - template: steps/azure_container_registry_purge.yml@templates
        parameters:
          dryRun: ${{ parameters.dryRun }}
          keepLastXDays: ${{ parameters.keepLastXDays }}
          repositories: "['appeal-planning-decision/appeals-service-api', 'appeal-planning-decision/auth-server', 'appeal-planning-decision/documents-api', 'appeal-planning-decision/forms-web-app', 'appeal-planning-decision/pdf-service-api']"
          resourceGroupsBySub: >
            {
              "dev": ["pins-rg-appeals-service-dev-uks-001", "pins-rg-appeals-service-dev-ukw-001"],
              "test": ["pins-rg-appeals-service-test-uks-001", "pins-rg-appeals-service-test-ukw-001"],
              "training": ["pins-rg-appeals-service-training-uks-001", "pins-rg-appeals-service-training-ukw-001"],
              "prod": ["pins-rg-appeals-service-prod-uks-001", "pins-rg-appeals-service-prod-ukw-001"]
            }
    workspace:
      clean: all
