const { PrismaClient } = require('@prisma/client');
const config = require('../configuration/config');

let primsaConfig = {
	datasourceUrl: config.db.sql.connectionString
};

// log sql queries generated by prisma
if (config.logger.level === 'debug') {
	primsaConfig.log = ['query'];
}

const dbClient = new PrismaClient(primsaConfig);

/**
 * @type {import('@prisma/client').PrismaClient}
 */
module.exports = dbClient;
