const { PrismaClient } = require('@prisma/client');
const config = require('../configuration/config');

let prismaConfig = {
	datasourceUrl: config.db.sql.connectionString
};

// log sql queries generated by prisma
if (config.logger.level === 'debug') {
	prismaConfig.log = ['query'];
}

let prisma;

/**
 * @returns {import('@prisma/client').PrismaClient}
 */
const createPrismaClient = () => {
	if (prisma) {
		return prisma;
	}

	prisma = new PrismaClient(prismaConfig);
	return prisma;
};

module.exports = { createPrismaClient };
