const express = require('express');
const taskListRouter = require('./task-list');
const checkAnswersRouter = require('./check-your-answers');
const contactDetailsRouter = require('./contact-details');
const applicationFormRouter = require('./application-form');
const applicationCertificatesIncludedRouter = require('./application-certificates-included');
const certificatesRouter = require('./certificates');
const applicationNumberRouter = require('./application-number');
const designAccessStatementRouter = require('./design-access-statement');
const designAccessStatementSubmittedRouter = require('./design-access-statement-submitted');
const appealSiteAddressRouter = require('./appeal-site-address');
const applicantNameRouter = require('./applicant-name');
const decisionLetterRouter = require('./decision-letter');
const appealStatementRouter = require('./appeal-statement');
const originalApplicantRouter = require('./original-applicant');
const ownSomeOfTheLandRouter = require('./own-some-of-the-land');
const ownAllTheLandRouter = require('./own-all-the-land');
const knowTheOwnersRouter = require('./know-the-owners');
const agriculturalHoldingRouter = require('./agricultural-holding');
const areYouATenantRouter = require('./are-you-a-tenant');
const otherTenantsRouter = require('./other-tenants');
const declarationRouter = require('./declaration');
const appealSubmittedRouter = require('./appeal-submitted');
const declarationInformationRouter = require('./declaration-information');
const visibleFromRoadRouter = require('./visible-from-road');
const healthSafetyIssuesRouter = require('./health-safety-issues');
const identifyingTheOwnersRouter = require('./identifying-the-owners');
const plansDrawingsRouter = require('./plans-drawings');
const newDocumentsRouter = require('./new-documents');
const newPlansDrawingsRouter = require('./new-plans-drawings');
const otherSupportingDocumentsRouter = require('./other-supporting-documents');
const tellingTheLandownersRouter = require('./telling-the-landowners');
const tellingTheTenantsRouter = require('./telling-the-tenants');
const howDecideAppealRouter = require('./how-decide-appeal');
const whyHearingRouter = require('./why-hearing');
const whyInquiryRouter = require('./why-inquiry');
const expectEnquiryLastRouter = require('./expect-inquiry-last');
const draftStatementOfCommonGroundRouter = require('./draft-statement-common-ground');
const advertisingYourAppealRouter = require('./advertising-your-appeal');
const plansDrawingsDocumentsRouter = require('./plans-drawings-documents');
const originalDecisionNoticeRouter = require('./original-decision-notice');
const proposedDevelopmentChanged = require('./proposed-development-changed');
const planningObligationPlannedRouter = require('./planning-obligation-planned');
const planningObligationStatusRouter = require('./planning-obligation-status');
const planningObligationDocumentsRouter = require('./planning-obligation');
const planningObligationDeadlineRouter = require('./planning-obligation-deadline');
const planningObligationDraftRouter = require('./draft-planning-obligation');
const letterConfirmingApplicationRouter = require('./letter-confirming-application');
const emailConfirmedRouter = require('./email-address-confirmed');
const cannotAppealRouter = require('./cannot-appeal');
const appealAlreadySubmittedRouter = require('./appeal-already-submitted');

const router = express.Router();

router.use(taskListRouter);
router.use(checkAnswersRouter);
router.use(contactDetailsRouter);
router.use(applicationFormRouter);
router.use(applicationCertificatesIncludedRouter);
router.use(certificatesRouter);
router.use(applicationNumberRouter);
router.use(designAccessStatementRouter);
router.use(designAccessStatementSubmittedRouter);
router.use(appealSiteAddressRouter);
router.use(applicantNameRouter);
router.use(decisionLetterRouter);
router.use(appealStatementRouter);
router.use(originalApplicantRouter);
router.use(ownSomeOfTheLandRouter);
router.use(ownAllTheLandRouter);
router.use(knowTheOwnersRouter);
router.use(agriculturalHoldingRouter);
router.use(areYouATenantRouter);
router.use(otherTenantsRouter);
router.use(declarationRouter);
router.use(appealSubmittedRouter);
router.use(declarationInformationRouter);
router.use(visibleFromRoadRouter);
router.use(healthSafetyIssuesRouter);
router.use(identifyingTheOwnersRouter);
router.use(plansDrawingsRouter);
router.use(newDocumentsRouter);
router.use(newPlansDrawingsRouter);
router.use(otherSupportingDocumentsRouter);
router.use(tellingTheLandownersRouter);
router.use(tellingTheTenantsRouter);
router.use(howDecideAppealRouter);
router.use(whyHearingRouter);
router.use(whyInquiryRouter);
router.use(expectEnquiryLastRouter);
router.use(draftStatementOfCommonGroundRouter);
router.use(advertisingYourAppealRouter);
router.use(plansDrawingsDocumentsRouter);
router.use(originalDecisionNoticeRouter);
router.use(proposedDevelopmentChanged);
router.use(planningObligationPlannedRouter);
router.use(planningObligationStatusRouter);
router.use(planningObligationDocumentsRouter);
router.use(planningObligationDraftRouter);
router.use(planningObligationDeadlineRouter);
router.use(letterConfirmingApplicationRouter);
router.use(emailConfirmedRouter);
router.use(cannotAppealRouter);
router.use(appealAlreadySubmittedRouter);

module.exports = router;
