const { JOURNEY_TYPES } = require('@pins/common/src/dynamic-forms/journey-types');

/**
 * @typedef {import('./journey-response').JourneyResponse} JourneyResponse
 */

const LPA_JOURNEY_TYPES_FORMATTED = {
	HAS: JOURNEY_TYPES.HAS_QUESTIONNAIRE,
	S78: JOURNEY_TYPES.S78_QUESTIONNAIRE,
	STATEMENT: JOURNEY_TYPES.S78_LPA_STATEMENT,
	FINAL_COMMENTS: JOURNEY_TYPES.S78_LPA_FINAL_COMMENTS
};

const APPELLANT_JOURNEY_TYPES_FORMATTED = {
	HAS: JOURNEY_TYPES.HAS_APPEAL_FORM,
	S78: JOURNEY_TYPES.S78_APPEAL_FORM,
	FINAL_COMMENTS: JOURNEY_TYPES.S78_APPELLANT_FINAL_COMMENTS,
	PROOF_EVIDENCE: JOURNEY_TYPES.S78_APPELLANT_PROOF_EVIDENCE
};

// TODO: move these out to common
module.exports = {
	LPA_JOURNEY_TYPES_FORMATTED,
	APPELLANT_JOURNEY_TYPES_FORMATTED
};
