trigger:
  paths:
    include:
      - packages/document-service-api
      - packages/common

pr:
  branches:
    include:
      - master
  paths:
    include:
      - packages/document-service-api
      - packages/common

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    azurecrName: $(azurecrName)
    authType: acr
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: packages/document-service-api/pipelines/azure-pipelines-variables.yml@self
    projectName: $(projectName)
    validateName: Build Test and Push
    validationSteps:
      - script: |
          buildName=$(versionNumber)_$(Build.BuildId)
          echo "Setting the name of the build to '$buildName'."
          echo "##vso[build.updatebuildnumber]$buildName"
        displayName: Set Build Number
      - template: steps/azure_web_app_acr_push.yml@templates
        parameters:
          azurecrName: $(azurecrName)
          dockerfilePath: $(dockerFilePath)
          repository: $(repository)
          testRunTitle: Document Service API Jest Tests
          versionNumber: $(versionNumber)
          workingDirectory: $(Build.Repository.LocalPath)
