name: Docker
description: Build and push a Docker image to a container registry
inputs:
  APP_DIR:
    description: App directory
    required: true
  APP_NAME:
    description: App name
    required: true
  DOCKER_PASSWORD:
    description: Docker password
    required: true
  DOCKER_REGISTRY:
    description: Docker registry URL
    required: true
  DOCKER_TAG:
    description: Docker tag to use
    required: true
  DOCKER_USERNAME:
    description: Docker username
    required: true
  VERSION:
    description: Version of the container
    required: true
runs:
  using: composite
  steps:
    - name: Log in to container registry
      shell: bash
      run: docker login "${{ inputs.DOCKER_REGISTRY }}" -u "${{ inputs.DOCKER_USERNAME }}" -p "${{ inputs.DOCKER_PASSWORD }}"

    - name: Build Docker image
      shell: bash
      run: docker build
        --build-arg="APP_NAME=${{ inputs.APP_NAME }}"
        --build-arg="BUILD_ID=$GITHUB_SHA"
        --build-arg="VERSION=${{ inputs.VERSION }}"
        -t ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.APP_NAME }}:${{ inputs.DOCKER_TAG }} ${{ inputs.APP_DIR }}

    - name: Push Docker image
      shell: bash
      run: |
        set -x
        echo "docker push ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.APP_NAME }}:${{ inputs.DOCKER_TAG }}"
        docker push ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.APP_NAME }}:${{ inputs.DOCKER_TAG }}
