# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - feature/as-3301
      - subtask/as-3374-horizon-householder-appeal-publish
  #   - master
  paths:
    include:
      - packages/horizon-functions

resources:
  - repo: self

name: '0.0.0' # set dynamically below in a task

variables:
  # VERSION INFO ----------------------------------------------------------
  version.MajorMinor: '1.0' # Manually adjust the version number as needed for semantic versioning. Revision is auto-incremented.
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  versionNumber: '$(version.MajorMinor).$(version.Revision)'
  # -----------------------------------------------------------------------

  # Container registry service connection established during pipeline creation
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:                                                     
  - stage: Build_Horizon_Functions
    displayName: Build and Deploy Horizon Functions
    jobs:
      - job: BuildHorizonFunctionsFunction
        pool:
          vmImage: $(vmImageName)
        displayName: Build Horizon Serverless Functions
        steps:
          - bash: |
              cd packages/horizon-functions
              npm install 
              npm run build --if-present
              npm prune --production
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/packages/horizon-functions"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build/horizon-functions.zip"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/horizon-functions.zip'
              artifactName: 'horizon-functions-artifact'
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'PINS ODTDEV (38602df9-8f79-41d1-a971-50c7672ba6f1)'
              appType: functionAppLinux
              appName: 'horizon-poc'
              package: $(System.DefaultWorkingDirectory)/build/horizon-functions.zip
              deploymentMethod: zipDeploy
