# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master

resources:
  - repo: self

name: '0.0.0' # set dynamically below in a task

variables:
  # VERSION INFO ----------------------------------------------------------
  version.MajorMinor: '1.0' # Manually adjust the version number as needed for semantic versioning. Revision is auto-incremented.
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  versionNumber: '$(version.MajorMinor).$(version.Revision)'
  simpleBranchName: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  branchTag: $[replace(variables['simpleBranchName'], '/', '_')]
  # -----------------------------------------------------------------------

  # Container registry service connection established during pipeline creation
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build_Horizon_Functions
    displayName: Build and Deploy Horizon Functions
    jobs:
      - job: BuildHorizonFunctionsFunction
        pool:
          vmImage: $(vmImageName)
        displayName: Build Horizon Serverless Functions
        steps:
          - bash: |
              cd packages/horizon-functions
              npm install
              npm run build --if-present
              npm prune --production
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/packages/horizon-functions"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build/horizon-functions.zip"
          - task: PublishBuildArtifacts@1
            displayName: Publish build artifact with latest tag
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/horizon-functions.zip'
              artifactName: 'horizon-functions-artifact-latest'
          - task: PublishBuildArtifacts@1
            displayName: Publish build artifact with branch name
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/horizon-functions.zip'
              artifactName: 'horizon-functions-artifact-$(branchTag)'
          - task: PublishBuildArtifacts@1
            displayName: Publish build artifact with version number
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/horizon-functions.zip'
              artifactName: 'horizon-functions-artifact-$(versionNumber)'
