---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: functions
  namespace: openfaas-fn
  annotations:
    fluxcd.io/automated: "true"

    filter.fluxcd.io/pingHorizon: semver:~1.0.0

    repository.fluxcd.io/horizon-add-document: functions.horizon-add-document.image
    filter.fluxcd.io/horizon-add-document: semver:~1.1.0
    tag.fluxcd.io/horizon-add-document: functions.horizon-add-document.tag

    repository.fluxcd.io/horizon-create-contact: functions.horizon-create-contact.image
    filter.fluxcd.io/horizon-create-contact: semver:~1.1.0
    tag.fluxcd.io/horizon-create-contact: functions.horizon-create-contact.tag

    repository.fluxcd.io/horizon-householder-appeal-publish: functions.horizon-householder-appeal-publish.image
    filter.fluxcd.io/horizon-householder-appeal-publish: semver:~1.3.0
    tag.fluxcd.io/horizon-householder-appeal-publish: functions.horizon-householder-appeal-publish.tag
spec:
  releaseName: functions
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/functions
  values:
    keyVault:
      name: pins-uks-vault-5989-prep

    pingHorizon:
      replicaCount: 1
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/ping
        tag: 1.0.0
      config:
        ping:
          url: http://10.0.7.4:8001/status

    functions:
      horizon-add-document:
        image: pinscommonukscontainers3887default.azurecr.io/horizon-add-document
        tag: 1.1.0
        envvars:
          DOCUMENT_SERVICE_URL: http://app.app-preprod.svc.cluster.local:3001
          HORIZON_URL: http://10.0.7.4:8000

      horizon-create-contact:
        image: pinscommonukscontainers3887default.azurecr.io/horizon-create-contact
        tag: 1.1.0
        envvars:
          HORIZON_URL: http://10.0.7.4:8000

      horizon-householder-appeal-publish:
        image: pinscommonukscontainers3887default.azurecr.io/horizon-householder-appeal-publish
        tag: 1.3.0
        envvars:
          APPEALS_SERVICE_URL: http://app.app-preprod.svc.cluster.local:3000
          DOCUMENT_SERVICE_URL: http://app.app-preprod.svc.cluster.local:3001
          GATEWAY_URL: http://gateway.openfaas.svc.cluster.local:8080
          HORIZON_URL: http://10.0.7.4:8000
