---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-preprod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/appealsServiceApi: semver:~1.0.0
    filter.fluxcd.io/documentServiceApi: semver:~1.0.0
    filter.fluxcd.io/formsWebApp: semver:~1.8.0
    filter.fluxcd.io/lpaQuestionnaireWebApp: semver:~1.0.0
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeals-service-api
        tag: 1.0.0

    documentServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/document-service-api
        tag: 1.0.0

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/forms-web-app
        tag: 1.8.0
      config:
        enableLimitedRouting: true
        googleAnalyticsId: G-W09HJL83FJ

    lpaQuestionnaireWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/lpa-questionnaire-web-app
        tag: latest

    keyVault:
      name: pins-uks-vault-5989-prep
      envSpecific:
        multiValueSecrets:
        - http-basic

    ingress:
      fwa:
        host: appeals-preprod.planninginspectorate.gov.uk
      lpaq:
        host: lpa-questions-dev.planninginspectorate.gov.uk
      httpBasic:
        enabled: true
        secret: akv-http-basic
