---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-preprod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/appealsServiceApi: semver:~2.2
    filter.fluxcd.io/documentServiceApi: semver:~1.1
    filter.fluxcd.io/formsWebApp: semver:~1.20
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeals-service-api
        tag: 2.2.0

    documentServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/document-service-api
        tag: 1.1.0

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/forms-web-app
        tag: 1.20.2

    keyVault:
      name: pins-uks-vault-5989-prep

    ingress:
      host: appeals-preprod.planninginspectorate.gov.uk
