@startuml
set separator none
title Appeals Back-Office Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("External Systems", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_1, "External Systems", $tags="External Systems") {
  System(GOVNotify, "GOV Notify", $descr="", $tags="", $link="")
}

AddBoundaryTag("Planning Inspectorate: Appeals", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_2, "Planning Inspectorate: Appeals", $tags="Planning Inspectorate: Appeals") {
  System(AppealsFrontOffice, "Appeals Front-Office", $descr="Public dashboards for appellants and LPAs", $tags="", $link="")
  System(AppealsBackOffice, "Appeals Back-Office", $descr="Internal service to manage planning appeals in England", $tags="", $link="")
  System(IntegrationLayer, "Integration Layer", $descr="Data exchange between FO and back office", $tags="", $link="")
  Person(Caseofficer, "Case officer", $descr="Validates and manages case data, documents and general appeal processing", $tags="", $link="")
  Person(Inspector, "Inspector", $descr="Inspects the appeal site and issues appeal decisions", $tags="", $link="")
}


Rel(AppealsFrontOffice, GOVNotify, "Requests emails to be sent", $techn="REST/HTTPS", $tags="", $link="")
Rel(AppealsBackOffice, GOVNotify, "Requests emails to be sent", $techn="REST/HTTPS", $tags="", $link="")
Rel(AppealsBackOffice, IntegrationLayer, "Records changes to appeals", $techn="Service Bus Topic", $tags="", $link="")
Rel(Caseofficer, AppealsBackOffice, "Manages cases", $techn="HTML/HTTPS", $tags="", $link="")
Rel(Inspector, AppealsBackOffice, "Decides cases", $techn="HTML/HTTPS", $tags="", $link="")
Rel(AppealsFrontOffice, AppealsBackOffice, "Peered VNets", $techn="Azure Private endpoint, Azure Private DNS zones, Azure VNet", $tags="", $link="")
Rel(AppealsFrontOffice, IntegrationLayer, "Informs back office of new appeals", $techn="Service Bus Topic", $tags="", $link="")

SHOW_LEGEND(true)
@enduml