@startuml
set separator none
title Integration Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System(AppealsFrontOffice, "Appeals Front-Office", $descr="Public dashboards for appellants and LPAs", $tags="", $link="")
System(AppealsBackOffice, "Appeals Back-Office", $descr="Internal service to manage planning appeals in England", $tags="", $link="")

Container_Boundary("IntegrationLayer.ServiceBus_boundary", "Service Bus", $tags="") {
  AddBoundaryTag("Commands", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_1, "Commands", $tags="Commands") {
    Component(IntegrationLayer.ServiceBus.ServiceBusAppealsubmissiontopic, "Service Bus Appeal submission topic", $techn="", $descr="Appeal submission commands", $tags="", $link="")
    Component(IntegrationLayer.ServiceBus.ServiceBusLPAsubmissiontopic, "Service Bus LPA submission topic", $techn="", $descr="LPA submission commands", $tags="", $link="")
  }

  AddBoundaryTag("Events", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_2, "Events", $tags="Events") {
    Component(IntegrationLayer.ServiceBus.ServiceBusAppealtopic, "Service Bus Appeal topic", $techn="", $descr="Appeal messages", $tags="", $link="")
    Component(IntegrationLayer.ServiceBus.ServiceBusDocumenttopic, "Service Bus Document topic", $techn="", $descr="Appeal document messages", $tags="", $link="")
    Component(IntegrationLayer.ServiceBus.ServiceBusServiceUsertopic, "Service Bus Service User topic", $techn="", $descr="Service user messages", $tags="", $link="")
    Component(IntegrationLayer.ServiceBus.ServiceBusEventtopic, "Service Bus Event topic", $techn="", $descr="Event message", $tags="", $link="")
  }

}

Rel(AppealsBackOffice, IntegrationLayer.ServiceBus.ServiceBusAppealtopic, "Records changes to appeals", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsBackOffice, IntegrationLayer.ServiceBus.ServiceBusDocumenttopic, "Records changes to documents", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsBackOffice, IntegrationLayer.ServiceBus.ServiceBusServiceUsertopic, "Records changes to user information", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsBackOffice, IntegrationLayer.ServiceBus.ServiceBusEventtopic, "Records changes to site visits and other events", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsFrontOffice, IntegrationLayer.ServiceBus.ServiceBusAppealtopic, "Poll for new messages", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsFrontOffice, IntegrationLayer.ServiceBus.ServiceBusDocumenttopic, "Poll for new messages", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsFrontOffice, IntegrationLayer.ServiceBus.ServiceBusServiceUsertopic, "Poll for new messages", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsFrontOffice, IntegrationLayer.ServiceBus.ServiceBusEventtopic, "Poll for new messages", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsFrontOffice, AppealsBackOffice, "Peered VNets", $techn="Azure Private endpoint, Azure Private DNS zones, Azure VNet", $tags="", $link="")
Rel(AppealsFrontOffice, IntegrationLayer.ServiceBus.ServiceBusAppealsubmissiontopic, "Informs back office of new appeals", $techn="Service Bus Topic", $tags="", $link="")
Rel(AppealsFrontOffice, IntegrationLayer.ServiceBus.ServiceBusLPAsubmissiontopic, "Informs back office of new lpaqs", $techn="Service Bus Topic", $tags="", $link="")

SHOW_LEGEND(true)
@enduml