---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/appealReplyServiceApi: semver:1.1.1
    filter.fluxcd.io/appealsServiceApi: semver:1.10.1
    filter.fluxcd.io/documentServiceApi: semver:1.3.0
    filter.fluxcd.io/formsWebApp: semver:1.30.6
    filter.fluxcd.io/lpaQuestionnaireWebApp: semver:1.6.2
    filter.fluxcd.io/pdfServiceApi: semver:1.0.1
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    appealReplyServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeal-reply-service-api
        tag: 1.1.1

    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeals-service-api
        tag: 1.10.0
      config:
        notify:
          secretName: akv-notify-prod
          templateId: 83c02ec6-c2ec-4551-86b3-807d4f203e19

    documentServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/document-service-api
        tag: 1.3.0

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/forms-web-app
        tag: 1.30.6
      config:
        googleAnalyticsId: UA-187490521-3

    lpaQuestionnaireWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/lpa-questionnaire-web-app
        tag: 1.6.2

    pdfServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/pdf-service-api
        tag: 1.0.1

    gotenberg:
      replicaCount: 2

    keyVault:
      name: pins-uks-vault-8439-prod

    pinsKeyVault:
      envSpecific:
        secrets:
        - notify-prod

    ingress:
      hosts:
        fwa:
          host: appeal-planning-decision.planninginspectorate.gov.uk
        lpaq:
          host: lpa-questionnaire.planninginspectorate.gov.uk

    horizon-householder-appeal-publish:
      amqp:
        connection:
          host: pins-uks-message-queue-prod.servicebus.windows.net
          hostname: pins-uks-message-queue-prod.servicebus.windows.net
