---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: app-prod
  annotations:
    fluxcd.io/automated: 'false'
spec:
  releaseName: app
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/app
  rollback:
    enable: true
  values:
    globals:
      domainNames:
        appealsWebApp: appeal-planning-decision.planninginspectorate.gov.uk
        lpaQuestionnaireWebApp: lpa-questions.planninginspectorate.gov.uk

    appealReplyServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeal-reply-service-api
        tag: 1.1.1
      config:
        notify:
          secretName: akv-notify-prod
          emailReplyToId:
            appealReplyNotificationEmailToLpa: cc6c4dd4-6c10-4b80-a045-0c9fb797d926
          templates:
            appealReplyNotificationEmailToLpa: d275326e-917b-404e-9702-fddd708bdb1f

    appealsServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/appeals-service-api
        tag: 1.19.0
      config:
        notify:
          secretName: akv-notify-prod
          emailReplyToId:
            startEmailToLpa: cc6c4dd4-6c10-4b80-a045-0c9fb797d926
          templateId: 83c02ec6-c2ec-4551-86b3-807d4f203e19
          templates:
            appealNotificationEmailToLpa: b8c7a449-3bc1-4ce1-b07c-4e90f4bd9c17
            appealSubmissionConfirmationEmailToAppellant: 27cddb5b-aa1e-453e-a511-f8eab31c3bb3
            startEmailToLpa: 22a6d662-3bbe-404f-8bca-c4b5c67ad346

    documentServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/document-service-api
        tag: 1.4.0

    formsWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/forms-web-app
        tag: 1.52.11
      config:
        googleAnalyticsId: UA-187490521-3

    lpaQuestionnaireWebApp:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/lpa-questionnaire-web-app
        tag: 1.6.2
      config:
        allowCreate: false

    pdfServiceApi:
      replicaCount: 2
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/pdf-service-api
        tag: 1.0.1

    queueRetryService:
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/queue-retry
        tag: 1.0.0

    gotenberg:
      replicaCount: 2

    keyVault:
      name: pins-uks-vault-8439-prod

    pinsKeyVault:
      envSpecific:
        secrets:
          - notify-prod

    ingress:
      hosts:
        fwa:
          host: appeal-planning-decision.planninginspectorate.gov.uk
        lpaq:
          host: lpa-questionnaire.planninginspectorate.gov.uk

    horizon-householder-appeal-publish:
      image:
        repository: pinscommonukscontainers3887default.azurecr.io/openfaas-amqp1.0-connector
        tag: 1.0.0
      amqp:
        connection:
          host: pins-uks-message-queue-prod.servicebus.windows.net
          hostname: pins-uks-message-queue-prod.servicebus.windows.net
