variables:
  # VERSION INFO ----------------------------------------------------------
  version.MajorMinor: '1.0' # Manually adjust the version number as needed for semantic versioning. Revision is auto-incremented.
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  versionNumber: $(version.MajorMinor).$(version.Revision)
  # -----------------------------------------------------------------------

  dockerFilePath: $(Build.SourcesDirectory)/packages/appeals-service-api/Dockerfile
  repository: appeal-planning-decision/appeals-service-api
  webAppNamePrefix: pins-app-appeals-service-appeal-reply-api
