trigger:
  paths:
    include:
      - packages/appeal-reply-service-api
      - packages/common
      - packages/business-rules

pr:
  branches:
    include:
      - master
  paths:
    include:
      - packages/appeal-reply-service-api
      - packages/common
      - packages/business-rules

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/1.2.0

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    azurecrName: $(azurecrName)
    authType: acr
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: packages/appeal-reply-service-api/pipelines/azure-pipelines-variables.yml@self
    projectName: $(projectName)
    validateName: Build Test and Push
    validationSteps:
      - script: |
          buildName=$(versionNumber)_$(Build.BuildId)
          echo "Setting the name of the build to '$buildName'."
          echo "##vso[build.updatebuildnumber]$buildName"
        displayName: Set Build Number
      - template: steps/azure_web_app_acr_push.yml@templates
        parameters:
          azurecrName: $(azurecrName)
          dockerfilePath: $(dockerFilePath)
          repository: $(repository)
          runTests: true
          testRunTitle: Appeal Reply Service API Jest Tests
          versionNumber: $(versionNumber)
          workingDirectory: $(Build.Repository.LocalPath)
