controller:
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: linux
  service:
    externalTrafficPolicy: Local
  config:
    http-redirect-code: "301"
    add-headers: nginx-ingress/custom-response-headers
    hide-headers: x-powered-by
    proxy-body-size: "0"
defaultBackend:
  enabled: false
  nodeSelector:
    kubernetes.io/os: linux
rbac:
  create: true
