const APPEAL_ID = {
  ENFORCEMENT_NOTICE: '1000',
  HOUSEHOLDER: '1001',
  ENFORCEMENT_LISTED_BUILDING: '1002',
  ADVERTISEMENT: '1003',
  PLANNING_OBLIGATION: '1004',
  PLANNING_SECTION_78: '1005',
  PLANNING_LISTED_BUILDING: '1006',
  COMMERCIAL: '1007',
  MINOR_COMMERCIAL: '1008',
  HEDGEROW: '1009',
  HIGH_HEDGES: '1010',
  FAST_TRACK_TREES: '1011',
};

const PROCEDURE_TYPE = {
  WRITTEN_REPRESENTATION: 'Written Representation',
  HEARING: 'Hearing',
  INQUIRY: 'Inquiry',
};

module.exports = {
  APPEAL_ID,
  PROCEDURE_TYPE,
};
