parameters:
  - name: region
    displayName: Region
    type: string
    values:
      - UK West
      - UK South
    default: UK West

trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/2.5.1
  pipelines:
    - pipeline: pdf-service-api-ci
      source: pdf-service-api CI
      trigger: 
        branches:
          include: 
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Stage
        deploymentSteps:
          - template: ../steps/azure_web_app_deploy.yml
            parameters:
              appName: $(webAppName)
              appResourceGroup: $(resourceGroup)
              appSlotName: staging
              azurecrName: $(azurecrName)
              repository: $(repository)
      - name: Deploy
        dependsOn:
          - Stage
        deploymentSteps:
          - template: ../steps/azure_web_app_slot_swap.yml
            parameters:
              appName: $(webAppName)
              appResourceGroup: $(resourceGroup)
              appStagingSlotName: staging
              appTargetSlotName: production
    globalVariables:
      - template: azure-pipelines-variables.yml@self
      - template: packages/pdf-service-api/pipelines/azure-pipelines-variables.yml@self
