trigger:
  branches:
    include:
      - main
  paths:
    include:
      - packages/business-rules

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Applications Token
      name: Planning-Inspectorate/common-pipeline-templates

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    azurecrName: $(azurecrName)
    authType: acr
    globalVariables:
      - template: pipelines/common/variables.yml@self
      - template: pipelines/variables.yml@self
    projectName: $(projectName)
    validateName: Build and Push
    validationSteps:
      - script: |
          buildName=$(versionNumber)_$(Build.BuildId)
          echo "Setting the name of the build to '$buildName'."
          echo "##vso[build.updatebuildnumber]$buildName"
        displayName: Set Build Number
      - task: AzureCLI@2
        displayName: Build and Push Docker Image to ACR
        inputs:
          azureSubscription: appeal-planning-decision-tooling
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login --name $(azurecrName)

            docker build . -t $(azurecrName).azurecr.io/$(repository):latest

            docker push -a $(azurecrName).azurecr.io/$(repository)
          workingDirectory: $(Build.Repository.LocalPath)/packages/business-rules
