parameters:
  - name: deploymentTag
    displayName: Deployment Tag
    type: string
    default: none
  - name: environments
    displayName: Environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test
  - name: region
    displayName: Region
    type: string
    values:
      - uks
      - ukw
    default: ukw

trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Appeals Token
      name: Planning-Inspectorate/common-pipeline-templates
  pipelines:
    - pipeline: document-service-api-ci
      source: document-service-api CI
      trigger: 
        branches:
          include: 
            - master

extends:
  template: stages/wrapper_web_app_cd.yml@templates
  parameters:
    appName: pins-app-appeals-service-documents-api-$(ENVIRONMENT)-${{ parameters.region }}-001
    artifactSourcePipeline: document-service-api CI
    azurecrName: $(azurecrName)
    azurecrServiceConnection: $(azurecrServiceConnection)
    deploymentTag: ${{ parameters.deploymentTag }}
    globalVariables:
      - template: pipelines/document-service-api/variables.yml@self
      - template: pipelines/variables.yml@self  
    projectName: $(projectName) 
    releaseVersion: $(version.MajorMinor)
    repository: $(repository)
    ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'ResourceTrigger') }}:
      environments:
        - name: Dev
    ${{ else }}:
      environments: ${{ parameters.environments }}
