@smoketest @e2e
Feature: As an Appellant/Agent
  I want to be able to change my answers
  So that my appeal is accurate

  Background:
    Given appellant has completed full appeal eligibility journey

  Scenario Outline: <Acceptance_criteria>- <description> for contact details section
    Given the appellant has provided details for '<contact_details>' and status is 'COMPLETED'
    And appellant provides the details for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>' and status is 'COMPLETED'
    And appellant provides the details about '<appeal_decision>' preference and status is 'COMPLETED'
    And appellant uploads documents from planning application and design and access statement as '<design_access_statement>' and status is 'COMPLETED'
    And appellant uploads documents for appeal for plans and drawings '<plans_and_drawings>' and supporting documents '<supporting_documents>' and status is 'COMPLETED'
    When appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<contact_details>'
    And appellant is displayed answers for appeal site for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>'
    And appellant is displayed answers for deciding your appeal for '<appeal_decision>'
    And appellant is displayed answers for planning application for '<design_access_statement>'
    And appellant is displayed answers for appeal for '<plans_and_drawings>' and '<supporting_documents>'
    When appellant selects to change answers for '<change_link_question>'
    And appellant provides the '<change_answer>' for contact details section
    And appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<change_link_question>' for '<change_answer>' for contact details section

    Examples:
      | Acceptance_criteria | description                                              | contact_details | own_land | own_some_land | owns_rest_of_land                 | agricultural_holding | tenant | other_tenants | health_and_safety | visible_publicLand | appeal_decision         | design_access_statement | plans_and_drawings | supporting_documents | change_link_question                            | change_answer                                                                                                                                                   |
      | AC-01               | Appellant changes answer to agent from appellant         | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Was the planning application made in your name? | agent                                                                                                                                                           |
      | AC-02               | Agent - Appellant changes answer to appellant from agent | agent           | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Was the planning application made in your name? | appellant                                                                                                                                                       |
      | AC-03               | Appellant changes contact details for appellant          | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Your contact details                            | appellant_new_contact, New Appellant Molly, New Appellant test company Ltd, new-appellant@gmail.com                                                             |
      | AC-04               | Appellant changes contact details for agent              | agent           | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Appeal made on behalf of                        | agent_appeal_on_behalf_of, New Appellant Molly, New Appellant test company Ltd, new Agent Zoopla, New Agent Zoopla Test Company Ltd, new-agent-zoopla@gmail.com |
      | AC-05               | Appellant changes contact details for agent              | agent           | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Your contact details                            | agent_new_contact, new Agent Zoopla, New Agent Zoopla Test Company Ltd, new-agent-zoopla@gmail.com                                                              |


  Scenario Outline: <Acceptance_criteria>- <description> for appeal site section
    Given the appellant has provided details for '<contact_details>' and status is 'COMPLETED'
    And appellant provides the details for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>' and status is 'COMPLETED'
    And appellant provides the details about '<appeal_decision>' preference and status is 'COMPLETED'
    And appellant uploads documents from planning application and design and access statement as '<design_access_statement>' and status is 'COMPLETED'
    And appellant uploads documents for appeal for plans and drawings '<plans_and_drawings>' and supporting documents '<supporting_documents>' and status is 'COMPLETED'
    When appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<contact_details>'
    And appellant is displayed answers for appeal site for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>'
    And appellant is displayed answers for deciding your appeal for '<appeal_decision>'
    And appellant is displayed answers for planning application for '<design_access_statement>'
    And appellant is displayed answers for appeal for '<plans_and_drawings>' and '<supporting_documents>'
    When appellant selects to change answers for '<change_link_question>'
    And appellant provides the '<change_answer>' for '<change_link_question>' for appeal site section
    And appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<change_link_question>' for '<change_answer>' for appeal site section

    Examples:
      | Acceptance_criteria | description                                                                                                                                   | contact_details | own_land | own_some_land | owns_rest_of_land                          | agricultural_holding | tenant | other_tenants | health_and_safety | visible_publicLand | appeal_decision         | design_access_statement | plans_and_drawings | supporting_documents | change_link_question                                              | change_answer                                          |
      | AC-06               | Appellant changes site address                                                                                                                | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Appeal site address                                               | 15 Foxland Road: Kirkham: Preston: Lancashire: PR8 6RL |
      | AC-07               | Appellant changes the answer for visible from public land from 'yes' to 'no'                                                                  | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Visible from a public road                                        | no                                                     |
      | AC-08               | Appellant changes the answer for visible from public land from 'no' to 'yes'                                                                  | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | no                 | Written representations | no                      | no                 | no                   | Visible from a public road                                        | yes                                                    |
      | AC-09               | Appellant changes the answer for Health and safety issues from 'yes' to 'no'                                                                  | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | yes               | yes                | Written representations | no                      | no                 | no                   | Health and safety issues                                          | no                                                     |
      | AC-10               | Appellant changes the answer for Health and safety issues from 'no' to 'yes'                                                                  | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Health and safety issues                                          | yes                                                    |
      | AC-11               | Appellant changes the answer for appeal site part of agricultural holding from 'No' to 'Yes' and appellant is not a tenant                    | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Is the appeal site part of an agricultural holding?               | yes, no                                                |
      | AC-12               | Appellant changes the answer for appeal site part of agricultural holding from 'Yes' to 'No'                                                  | appellant       | yes      | no            | Yes, I know who owns all the land          | yes                  | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Is the appeal site part of an agricultural holding?               | no                                                     |
      | AC-13               | Appellant changes the answer for are you a tenant of agricultural holding from 'No' to 'Yes'                                                  | appellant       | yes      | no            | Yes, I know who owns all the land          | yes                  | no     | yes           | no                | no                 | Written representations | no                      | no                 | no                   | Are you a tenant of the agricultural holding?                     | yes                                                    |
      | AC-14               | Appellant changes the answer for are you a tenant of agricultural holding from 'Yes' to 'No'                                                  | appellant       | yes      | no            | Yes, I know who owns all the land          | yes                  | yes    | yes           | yes               | yes                | Written representations | no                      | no                 | no                   | Are you a tenant of the agricultural holding?                     | no                                                     |
      | AC-15               | Appellant changes the answer for are there any other tenants from 'no' to 'yes'                                                               | appellant       | yes      | no            | Yes, I know who owns all the land          | yes                  | yes    | no            | no                | yes                | Written representations | no                      | no                 | no                   | Are there any other tenants?                                      | yes                                                    |
      | AC-16               | Appellant changes the answer for are there any other tenants from 'yes' to 'no'                                                               | appellant       | yes      | no            | Yes, I know who owns all the land          | yes                  | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Are there any other tenants?                                      | no                                                     |
      | AC-17               | Appellant changes the answer Own all the land from 'no' to 'yes', appellant owns some land and appellant knows who own some of the land       | appellant       | no       | yes           | I know who owns some of the land           | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you own the land involved in the appeal?                       | yes                                                    |
      | AC-18               | Appellant changes the answer Own all the land from 'yes' to 'no', appellant owns some land and appellant knows who own all the land           | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you own the land involved in the appeal?                       | no: yes: Yes, I know who owns all the land             |
      | AC-19               | Appellant changes the answer Own all the land from 'yes' to 'no', appellant owns some land and appellant knows who own some of the land       | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you own the land involved in the appeal?                       | no: yes: I know who owns some of the land              |
      | AC-20               | Appellant changes the answer Own all the land from 'yes' to 'no', appellant owns some land and appellant doesn't know who owns the land       | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you own the land involved in the appeal?                       | no: yes: No, I do not know who owns any of the land    |
      | AC-21               | Appellant changes the answer for who owns rest of the land to 'I know who owns some of the land'                                              | appellant       | no       | no            | No, I do not know who owns any of the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you know who owns the land involved in the appeal?             | I know who owns some of the land                       |
      | AC-22               | Appellant changes the answer for who owns rest of the land to 'Yes, I know who owns all the land'                                             | appellant       | no       | no            | I know who owns some of the land           | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you know who owns the land involved in the appeal?             | Yes, I know who owns all the land                      |
      | AC-23               | Appellant changes the answer for who owns rest of the land to 'No, I do not know who owns any of the land'                                    | appellant       | no       | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you know who owns the land involved in the appeal?             | No, I do not know who owns any of the land             |
      | AC-24               | Appellant changes the answer Own all the land from 'yes' to 'no', appellant doesn't own the land and appellant knows who own all the land     | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you own the land involved in the appeal?                       | no: no: Yes, I know who owns all the land              |
      | AC-25               | Appellant changes the answer Own all the land from 'yes' to 'no', appellant doesn't own the land and appellant knows who own some of the land | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you own the land involved in the appeal?                       | no: no: I know who owns some of the land               |
      | AC-26               | Appellant changes the answer Own all the land from 'yes' to 'no', appellant doesn't own the land and appellant doesn't know who owns the land | appellant       | yes      | no            | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you own the land involved in the appeal?                       | no: no: No, I do not know who owns any of the land     |
      | AC-27               | Appellant changes the answer for who owns the land to 'I know who owns some of the land'                                                      | appellant       | no       | yes           | No, I do not know who owns any of the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you know who owns the rest of the land involved in the appeal? | I know who owns some of the land                       |
      | AC-28               | Appellant changes the answer for who owns the land to 'Yes, I know who owns all the land'                                                     | appellant       | no       | yes           | I know who owns some of the land           | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you know who owns the rest of the land involved in the appeal? | Yes, I know who owns all the land                      |
      | AC-29               | Appellant changes the answer for who owns the land to 'No, I do not know who owns any of the land'                                            | appellant       | no       | yes           | Yes, I know who owns all the land          | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Do you know who owns the rest of the land involved in the appeal? | No, I do not know who owns any of the land             |


  Scenario Outline: <Acceptance_criteria>- <description> for deciding your appeal section
    Given the appellant has provided details for '<contact_details>' and status is 'COMPLETED'
    And appellant provides the details for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>' and status is 'COMPLETED'
    And appellant provides the details about '<appeal_decision>' preference and status is 'COMPLETED'
    And appellant uploads documents from planning application and design and access statement as '<design_access_statement>' and status is 'COMPLETED'
    And appellant uploads documents for appeal for plans and drawings '<plans_and_drawings>' and supporting documents '<supporting_documents>' and status is 'COMPLETED'
    When appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<contact_details>'
    And appellant is displayed answers for appeal site for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>'
    And appellant is displayed answers for deciding your appeal for '<appeal_decision>'
    And appellant is displayed answers for planning application for '<design_access_statement>'
    And appellant is displayed answers for appeal for '<plans_and_drawings>' and '<supporting_documents>'
    When appellant selects to change answers for '<change_link_question>'
    And appellant provides the '<change_answer>' for '<change_link_question>' for deciding your appeal section
    And appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<change_link_question>' for '<change_answer>' for deciding your appeal section

    Examples:
      | Acceptance_criteria | description                                           | contact_details | own_land | own_some_land | owns_rest_of_land                 | agricultural_holding | tenant | other_tenants | health_and_safety | visible_publicLand | appeal_decision         | design_access_statement | plans_and_drawings | supporting_documents | change_link_question                                | change_answer                                                                     |
      | AC-30               | Appellant changes Written representations to Inquiry  | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | How would you prefer us to decide your appeal?      | Inquiry                                                                           |
      | AC-31               | Appellant changes Hearing to Written representations  | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Hearing                 | no                      | no                 | no                   | How would you prefer us to decide your appeal?      | Written representations                                                           |
      | AC-32               | Appellant changes Inquiry to Hearing                  | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Inquiry                 | no                      | no                 | no                   | How would you prefer us to decide your appeal?      | Hearing                                                                           |
      | AC-33               | Appellant changes Written representations to Hearing  | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | How would you prefer us to decide your appeal?      | Hearing                                                                           |
      | AC-34               | Appellant changes Hearing to Inquiry                  | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Hearing                 | no                      | no                 | no                   | How would you prefer us to decide your appeal?      | Inquiry                                                                           |
      | AC-35               | Appellant changes Inquiry to Written representations  | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Hearing                 | no                      | no                 | no                   | How would you prefer us to decide your appeal?      | Written representations                                                           |
      | AC-36               | Appellant changes Hearing reason                      | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Hearing                 | no                      | no                 | no                   | Why would you prefer a hearing?                     | I want to provide new information and facts of the Appeal for the formal decision |
      | AC-37               | Appellant changes Hearing statement for common ground | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Hearing                 | no                      | no                 | no                   | Draft statement of common ground                    | upload-file-valid.jpg, Hearing                                                    |
      | AC-38               | Appellant changes Inquiry reason                      | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Inquiry                 | no                      | no                 | no                   | Why would you prefer an inquiry?                    | I want to provide new information and facts of the Appeal for the formal decision |
      | AC-39               | Appellant changes number of days for inquiry          | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Inquiry                 | no                      | no                 | no                   | How many days would you expect the inquiry to last? | 5                                                                                 |
      | AC-40               | Appellant changes Inquiry statement for common ground | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Inquiry                 | no                      | no                 | no                   | Draft statement of common ground                    | upload-file-valid.jpg, Inquiry                                                    |

  Scenario Outline: <Acceptance_criteria>- <description> for planning application section
    Given the appellant has provided details for '<contact_details>' and status is 'COMPLETED'
    And appellant provides the details for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>' and status is 'COMPLETED'
    And appellant provides the details about '<appeal_decision>' preference and status is 'COMPLETED'
    And appellant uploads documents from planning application and design and access statement as '<design_access_statement>' and status is 'COMPLETED'
    And appellant uploads documents for appeal for plans and drawings '<plans_and_drawings>' and supporting documents '<supporting_documents>' and status is 'COMPLETED'
    When appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<contact_details>'
    And appellant is displayed answers for appeal site for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>'
    And appellant is displayed answers for deciding your appeal for '<appeal_decision>'
    And appellant is displayed answers for planning application for '<design_access_statement>'
    And appellant is displayed answers for appeal for '<plans_and_drawings>' and '<supporting_documents>'
    When appellant selects to change answers for '<change_link_question>'
    And appellant provides the '<change_answer>' for '<change_link_question>' for planning application section
    And appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<change_link_question>' for '<change_answer>' for planning application section

    Examples:
      | Acceptance_criteria | description                                                                             | contact_details | own_land | own_some_land | owns_rest_of_land                 | agricultural_holding | tenant | other_tenants | health_and_safety | visible_publicLand | appeal_decision         | design_access_statement | plans_and_drawings | supporting_documents | change_link_question                                   | change_answer               |
      | AC-41               | Appellant changes Planning application form                                             | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Planning application form                              | upload-file-valid.pdf       |
      | AC-42               | Appellant changes Planning application number                                           | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Planning application number                            | po-98765                    |
      | AC-43               | Appellant changes Plans, drawings and supporting documents                              | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Plans, drawings and supporting documents               | upload-file-valid.jpeg      |
      | AC-44               | Appellant changes Design and access statement submitted with application from No to Yes | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Design and access statement submitted with application | yes                         |
      | AC-45               | Appellant changes Design and access statement submitted with application from Yes to no | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | yes                     | no                 | no                   | Design and access statement submitted with application | no                          |
      | AC-46               | Appellant changes Decision letter                                                       | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Decision letter                                        | upload-file-valid.jpeg      |
      | AC-47               | Appellant changes Design and access statement                                           | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | yes                     | no                 | no                   | Design and access statement                            | yes, upload-file-valid.jpeg |


  Scenario Outline: <Acceptance_criteria>- <description> for your appeal section
    Given the appellant has provided details for '<contact_details>' and status is 'COMPLETED'
    And appellant provides the details for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>' and status is 'COMPLETED'
    And appellant provides the details about '<appeal_decision>' preference and status is 'COMPLETED'
    And appellant uploads documents from planning application and design and access statement as '<design_access_statement>' and status is 'COMPLETED'
    And appellant uploads documents for appeal for plans and drawings '<plans_and_drawings>' and supporting documents '<supporting_documents>' and status is 'COMPLETED'
    When appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<contact_details>'
    And appellant is displayed answers for appeal site for '<own_land>', '<own_some_land>', '<owns_rest_of_land>', '<agricultural_holding>', '<visible_publicLand>', '<tenant>', '<other_tenants>' and '<health_and_safety>'
    And appellant is displayed answers for deciding your appeal for '<appeal_decision>'
    And appellant is displayed answers for planning application for '<design_access_statement>'
    And appellant is displayed answers for appeal for '<plans_and_drawings>' and '<supporting_documents>'
    When appellant selects to change answers for '<change_link_question>'
    And appellant provides the '<change_answer>' for '<change_link_question>' for your appeal section
    And appellant clicks on Check your answers link
    Then appellant is displayed the check your answer page
    And appellant is displayed answers for '<change_link_question>' for '<change_answer>' for your appeal section

    Examples:
      | Acceptance_criteria | description                                                                       | contact_details | own_land | own_some_land | owns_rest_of_land                 | agricultural_holding | tenant | other_tenants | health_and_safety | visible_publicLand | appeal_decision         | design_access_statement | plans_and_drawings | supporting_documents | change_link_question                         | change_answer               |
      | AC-48               | Appellant changes Appeal statement                                                | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Appeal statement                             | upload-file-valid.pdf       |
      | AC-49               | Appellant changes Any plans or drawings to support your appeal from 'No' to 'Yes' | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Any plans or drawings to support your appeal | yes                         |
      | AC-50               | Appellant changes Any plans or drawings to support your appeal from 'Yes' to 'No' | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | yes                | no                   | Any plans or drawings to support your appeal | no                          |
      | AC-51               | Appellant changes Any documents to support your appeal from 'No' to 'Yes'         | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | no                   | Any documents to support your appeal         | yes                         |
      | AC-52               | Appellant changes Any documents to support your appeal from 'Yes' to 'No'         | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | no                 | yes                  | Any documents to support your appeal         | no                          |
      | AC-53               | Appellant changes plans and drawings document                                     | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | no                      | yes                | no                   | Plans and drawings                           | yes, upload-file-valid.jpeg |
      | AC-54               | Appellant changes Supporting document                                             | appellant       | yes      | no            | Yes, I know who owns all the land | no                   | yes    | yes           | no                | yes                | Written representations | yes                     | no                 | yes                  | Supporting documents                         | yes, upload-file-valid.jpeg |
