{{- if .Values.pingHorizon.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "functions.fullname" . }}-ping-hzn-srv
  labels:
  {{- include "functions.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pingHorizon.replicaCount }}
  selector:
    matchLabels:
      {{- include "functions.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: {{ .Values.pingHorizon.config.port | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "functions.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pingHorizon.image.repository }}:{{ .Values.pingHorizon.image.tag }}"
          imagePullPolicy: {{ .Values.pingHorizon.image.pullPolicy }}
          ports:
            - name: ping-hzn-srv
              containerPort: {{ .Values.pingHorizon.config.port }}
              protocol: TCP
          # These are not true probes, but are used to generate the metrics
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: {{ div .Values.pingHorizon.config.ping.timeout 1000 }}
            httpGet:
              path: /ping
              port: ping-hzn-srv
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /ping
              port: ping-hzn-srv
          env:
            - name: APP_NAME
              value: {{ .Values.pingHorizon.config.serviceName }}
            - name: PING_METHOD
              value: {{ .Values.pingHorizon.config.ping.method | quote }}
            - name: PING_TIMEOUT
              value: {{ .Values.pingHorizon.config.ping.timeout | quote }}
            - name: PING_URL
              value: {{ .Values.pingHorizon.config.ping.url | quote }}
            - name: SERVER_PORT
              value: {{ .Values.pingHorizon.config.port | quote }}
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
