name: Kubectl Helm
description: Provides the Kubectl and Helm binaries
inputs:
  cmd:
    description: Command to run in the image
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.cmd }}
