BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[AppealCase] ALTER COLUMN [siteAddressLine1] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[AppealCase] ALTER COLUMN [siteAddressPostcode] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[AppealCase] ALTER COLUMN [siteAddressTown] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
