{{ $queueConfig := index .Values "horizon-householder-appeal-publish" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-appeal-reply-service-api
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.appealReplyServiceApi.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: {{ .Values.appealReplyServiceApi.config.port | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.appealReplyServiceApi.image.repository }}:{{ .Values.appealReplyServiceApi.image.tag }}"
          imagePullPolicy: {{ .Values.appealReplyServiceApi.image.pullPolicy }}
          ports:
            - name: {{ .Values.appealReplyServiceApi.service.name }}
              containerPort: {{ .Values.appealReplyServiceApi.config.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.appealReplyServiceApi.service.name }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.appealReplyServiceApi.service.name }}
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: LOGGER_LEVEL
              value: {{ .Values.appealReplyServiceApi.config.logLevel }}
            - name: MONGODB_DB_NAME
              value: appeal-reply-service-api
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  key: value
                  name: akv-mongodb-connection-url
            - name: SERVER_PORT
              value: {{ .Values.appealReplyServiceApi.config.port | quote }}
            - name: SERVER_TERMINATION_GRACE_PERIOD_SECONDS
              value: {{ 10 | quote }} # Same as "periodSeconds" for readinessProbe
            - name: HORIZON_HAS_PUBLISHER_HOST
              value: {{ $queueConfig.amqp.connection.host | quote }}
            - name: HORIZON_HAS_PUBLISHER_HOSTNAME
              value: {{ $queueConfig.amqp.connection.hostname | quote }}
            - name: HORIZON_HAS_PUBLISHER_RECONNECT_LIMIT
              value: {{ $queueConfig.amqp.connection.reconnectLimit | quote }}
            - name: HORIZON_HAS_PUBLISHER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ $queueConfig.amqp.connection.existingPasswordSecret | quote }}
            - name: HORIZON_HAS_PUBLISHER_PORT
              value: {{ $queueConfig.amqp.connection.port | quote }}
            - name: HORIZON_HAS_PUBLISHER_ATTEMPT_RECONNECTION
              value: {{ $queueConfig.amqp.connection.reconnect | quote }}
            - name: HORIZON_HAS_PUBLISHER_TRANSPORT
              value: {{ $queueConfig.amqp.connection.transport | quote }}
            - name: HORIZON_HAS_PUBLISHER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ $queueConfig.amqp.connection.existingUsernameSecret | quote }}
            - name: HORIZON_HAS_PUBLISHER_QUEUE
              value: {{ $queueConfig.amqp.receiver.source | quote }}
            - name: DOCUMENTS_SERVICE_API_URL
              value: "http://{{ include "app.fullname" . }}:{{ .Values.documentServiceApi.service.port }}"
            - name: APPEALS_SERVICE_API_URL
              value: "http://{{ include "app.fullname" . }}:{{ .Values.appealsServiceApi.service.port }}"
            - name: SRV_NOTIFY_BASE_URL
              value: {{ .Values.appealReplyServiceApi.config.notify.baseUrl | quote }}
            - name: SRV_NOTIFY_SERVICE_ID
              value: {{ .Values.appealReplyServiceApi.config.notify.serviceId | quote }}
            - name: SRV_NOTIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: value
                  name: {{ .Values.appealReplyServiceApi.config.notify.secretName }}
            - name: SRV_NOTIFY_TEMPLATE_ID_APPEAL_REPLY_SUBMISSION_CONFIRMATION
              value: {{ .Values.appealReplyServiceApi.config.notify.templates.appealReplyNotificationEmailToLpa | quote }}
            - name: SRV_NOTIFY_EMAIL_REPLYTO_ID_APPEAL_REPLY_SUBMISSION_CONFIRMATION
              value: {{ .Values.appealReplyServiceApi.config.notify.emailReplyToId.appealReplyNotificationEmailToLpa | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
