{{- $keyVaultName := .Values.keyVault.name -}}
{{- range .Values.keyVault.secrets }}
---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: akv-{{ . }}
spec:
  vault:
    name: {{ $keyVaultName }}
    object:
      name: {{ . }}
      type: secret
  output:
    secret:
      name: akv-{{ . }}
      dataKey: value
{{- end }}

{{- range .Values.keyVault.multiValueSecrets }}
---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: akv-{{ . }}
spec:
  vault:
    name: {{ $keyVaultName }}
    object:
      contentType: application/x-json
      name: {{ . }}
      type: multi-key-value-secret
  output:
    secret:
      name: akv-{{ . }}
{{- end }}
