name: Semantic Release
description: Perform the Semantic Release actions
inputs:
  DIR:
    description: Directory to run against
    required: true
  GET_VERSION:
    description: Workflow is to get the next version number
    required: false
    default: "false"
  GITHUB_TOKEN:
    description: GITHUB_TOKEN secret
    required: true
  SET_VERSION:
    description: Workflow is to set the next version number
    required: false
    default: "false"
outputs:
  new_release_published:
    description: Tells you if a new release is to be published - either "true" or "false"
    value: ${{ steps.get_version.outputs.new_release_published }}
  new_release_version:
    description: New release version - include package name
    value: ${{ steps.get_version.outputs.new_release_version }}
  new_release_version_number:
    description: New version number - in format vN.N.N
    value: ${{ steps.get_version.outputs.new_release_version_number }}
runs:
  using: composite
  steps:
    - name: Get version
      id: get_version
      shell: bash
      run: |
        NEW_VERSION_PUBLISHED=false
        NEW_VERSION=""
        NEW_VERSION_NUMBER=""
        if [ "${{ inputs.GET_VERSION }}" == "true" ]; then
          cd ${{ inputs.DIR }}
          export GITHUB_TOKEN="${{ inputs.GITHUB_TOKEN }}"

          NEW_VERSION=$(./node_modules/.bin/semantic-release -d | awk '/Release note for version/ { getline; print $2 }')

          if [ -n "$NEW_VERSION" ]; then
            NEW_VERSION_PUBLISHED=true
            NEW_VERSION_NUMBER=$(echo $NEW_VERSION | sed -En "s/.*-v(.*)/\1/p")
          fi
        fi

        echo "::set-output name=new_release_published::$NEW_VERSION_PUBLISHED"
        echo "::set-output name=new_release_version::$NEW_VERSION"
        echo "::set-output name=new_release_version_number::$NEW_VERSION_NUMBER"

    - name: Set version
      shell: bash
      run: |
        if [ "${{ inputs.SET_VERSION }}" == "true" ]; then
          cd ${{ inputs.DIR }}
          export GITHUB_TOKEN="${{ inputs.GITHUB_TOKEN }}"
          ./node_modules/.bin/semantic-release --ci
        fi
