# This package is never published, but it relied upon
# as a local npm dependency

name: Common Package

env:
  APP_DIR: common
  APP_NAME: common

defaults:
  run:
    working-directory: packages/common

on:
  pull_request:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'subtask/**'
    paths:
      - packages/common/**/*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci

      - run: npm run lint

      - run: npm test

      - run: npm run test:cov
