name: Cypress Report

env:
  CYPRESS_REPORTS: ./e2e-tests/cypress/cucumber-report
  CYPRESS_VIDEOS: ./e2e-tests/cypress/videos
  ACP_REPORTS: ./e2e-tests/cypress/reports/acp
  PINS_REPORTS: ./e2e-tests/cypress/reports/pins
  LPA_CYPRESS_REPORTS: ./lpa-submissions-e2e-tests/cypress/cucumber-report
  LPA_CYPRESS_VIDEOS: ./lpa-submissions-e2e-tests/cypress/videos
  LPA_REPORTS: ./lpa-submissions-e2e-tests/cypress/reports/lpa
  COMBINED_REPORTS: ./e2e-tests/cypress/reports

on:
  push:
    branches:
      - master
      - develop

jobs:

  cypress-report:
    name: "Cypress Report"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install the world
        run: make install

      - name: Start the world with ACP integration
        run: |
          export SERVER_LIMITED_ROUTING_ENABLED=true
          docker-compose up -d

      - name: Run the tests with ACP integration
        run: npm run test:e2e:acp

      - name: Post-process results with ACP integration
        if: ${{ always() }}
        run: npm run test:e2e:postprocess

      - name: Archive results with ACP integration
        if: ${{ always() }}
        uses: actions/upload-artifact@main
        with:
          name: results-acp
          path: ${{ env.CYPRESS_REPORTS }}

      - name: Archive videos with ACP integration
        if: ${{ always() }}
        uses: actions/upload-artifact@main
        with:
          name: videos-acp
          path: ${{ env.CYPRESS_VIDEOS }}

      - name: Move ACP test reports to combined reports folder
        run: cp -r ${{ env.CYPRESS_REPORTS }} ${{ env.ACP_REPORTS }}

      - name: Start the world without ACP integration i.e. PINS
        run: |
          export SERVER_LIMITED_ROUTING_ENABLED=false
          docker-compose up -d

      - name: Run the tests without ACP integration
        run: npm run test:e2e

      - name: Post-process results without ACP integration
        if: ${{ always() }}
        run: npm run test:e2e:postprocess

      - name: Archive results without ACP integration
        if: ${{ always() }}
        uses: actions/upload-artifact@main
        with:
          name: results-pins
          path: ${{ env.CYPRESS_REPORTS }}

      - name: Archive videos without ACP integration
        if: ${{ always() }}
        uses: actions/upload-artifact@main
        with:
          name: videos-pins
          path: ${{ env.CYPRESS_VIDEOS }}

      - name: Move PINS test reports to combined reports folder
        run: cp -r ${{ env.CYPRESS_REPORTS }} ${{ env.PINS_REPORTS }}

      - name: Start the world for LPA
        run: |
          export SERVER_LIMITED_ROUTING_ENABLED=false
          docker-compose up -d

      - name: Run the tests for LPA
        run: npm run test:e2e:lpa

      - name: Post-process results for LPA
        if: ${{ always() }}
        run: npm run test:e2e:lpa:postprocess

      - name: Archive results for LPA
        if: ${{ always() }}
        uses: actions/upload-artifact@main
        with:
          name: results-lpa
          path: ${{ env.LPA_CYPRESS_REPORTS }}

      - name: Archive videos for LPA
        if: ${{ always() }}
        uses: actions/upload-artifact@main
        with:
          name: videos-lpa
          path: ${{ env.LPA_CYPRESS_VIDEOS }}

      - name: Move LPA test reports to combined reports folder
        run: cp -r ${{ env.LPA_CYPRESS_REPORTS }} ${{ env.LPA_REPORTS }}

      - name: Deploy Cypress test reports to github pages
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.COMBINED_REPORTS }}
          user_name: 'Karuna[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
